### ISSUE TITLE
Feature Suggestion - Add A Property To Adjust The MaxClockSlew

### ISSUE THREAD

**Issue by rhavlick** [IdentityModel/Thinktecture.IdentityModel.45#111]
If possible in a future release, could you please add a property to the Thinktecture.IdentityModel.Tokens.Http.AuthenticationConfiguration class that would allow the JwtSecurityTokenHandler.MaxClockSlew in the JwtSecurityTokenHandlerWrapper class to be adjusted.  (Maybe this could be done by adding a property also to the TokenValidationParameter that is passed in the JwtSecurityTokenHandlerWrapper's constructor).  

Currently the MaxClockSlew is 5 minutes to adjust between the AS and RS.  It they are on the same server the clock is most likely the same, and could allow the tokens to be invalidated in less than 5 minutes.

Thanks

**Comment by leastprivilege** [comment]
sorry - this repo is deprecated
