### ISSUE TITLE
Should work on mono: license issues/missing implementation

### ISSUE THREAD

**Issue by haf** [IdentityModel/Thinktecture.IdentityModel.45#145]
It seems that it's fairy hard to find guidance on how to validate the SAML2 and JWT token types on something other than Windows.

Since Microsoft.IdentityModel and all other IdentityService-code is licensed to only be run on Windows this is a problem. Also, none of the APIs of WIF have been implemented by the mono crew.

Example error:

```
Unhandled Exception:
System.TypeLoadException: Could not load type 'System.IdentityModel.Tokens.Saml2SecurityTokenHandler' from assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by riskypathak** [comment]
@haf 

Can you confirm that is this issue has been resolved?

I am still getting eror.

Could not load type 'Microsoft.Identityon: Could not load type 'Microsoft.IdentityModel.Tokens.Saml2SecurityTokenHandler' from assembly 'Microsoft.IdentityModel.Protocol
.Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by haf** [comment]
@riskypathak "System.IdentityModel" was added. It seems It ALL hasn't been added, after further testing, so I get a similar error to you.

**Comment by haf** [comment]
Here it is https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocol.Extensions/Saml2SecurityTokenHandler.cs though, so perhaps @leastprivilege could import it into the repo?

**Comment by jonathankarsh** [comment]
@haf I am facing a similar issue, would like to work with saml2 tokens on mono but getting exceptions.,
Should I:
1. Expect it to work with current (2.x) versions of idsrv? (Tried with v1.6 and no luck)
2. Use your last comment's link to azure AD,
Or
3. Dig deeper into the first link you posted for a SAML2 workaround?

The bigger "want" here is ADFS support in mono; am I in the right direction?

Thanks

**Comment by jonathankarsh** [comment]
Pushed to a more general forum: http://stackoverflow.com/questions/32634604/does-mono-support-adfs

**Comment by haf** [comment]
@jonathankarsh If you make [this PR happen](https://github.com/SuaveIO/suave/pull/142) together with us at Suave then I'll ensure the this (or similar) OAuth middleware works, one way or another – because that is my use-case.

**Comment by jonathankarsh** [comment]
Thanks @haf, I'll have a look, but I'm not sure how good my F# is...

**Comment by abelondev** [comment]
So can I run any of samples on mono/mac without windows access? I am stuck.
