### ISSUE TITLE
HAWK Sample Project does not work with the latest version of Thinktecture.IdentityModel

### ISSUE THREAD

**Issue by majhoos** [IdentityModel/Thinktecture.IdentityModel.45#160]
HawkAuthenticationHandler in “Thinktecture.IdentityModel.45-master > Samples > Hawk > Hawk.Samples.WebApi.Owin” no longer compiles as soon I install package Thinktecture.IdentityModel 3.6.1. As I can see you are using Thinktecture.IdentityModel.45 version 3.6.1.0. Although there is an entry for this package in nuget store but it also warns : “The owner has unlisted this package. This could mean that the package is deprecated or shouldn’t be used anymore.”. Could you please update the code to use the latest Thinktecture.IdentityModel 3.6.1 rather than the Thinktecture.IdentityModel.45.
In addition it appears that the latest version of Microsoft.Owin.Security has updated some of the definition and types such as AuthenticationExtra are no longer available or have been relocated.
Could you please update all the packages and resolve all the compilation issues.

**Comment by leastprivilege** [comment]
sorry - this repo is deprecated.
