### ISSUE TITLE
CertificateWSTrustBinding: how to sign body

### ISSUE THREAD

**Issue by thuannguy** [IdentityModel/Thinktecture.IdentityModel.45#161]
Hi,
I'm using CertificateWSTrustBinding with TransportWithMessageCredential to send RequestSecurityToken request to an STS. My problem is that the STS requires that the message body must be signed which is doesn't supported by that binding. Do you have any hint about how to achieve that request with Thinktecture.IdentityModel?
Thanks for reading :)

**Comment by leastprivilege** [comment]
TransportWithMessageCredential is transport security - you can try the Message security mode. Otherwise you need to construct a custom binding.

**Comment by thuannguy** [comment]
I had to use a custom binding in the end: Message with AsymmetricSecurityBinding and HttpsTransport. It seems there is no other alternative.
Thank you for reading and answering my question :)
