### ISSUE TITLE
Access Principal when using BasicAuthentication

### ISSUE THREAD

**Issue by rschenkel** [IdentityModel/Thinktecture.IdentityModel.45#163]
Is there a way to get access to the Http request and incoming principal in the delegate when using basic authentication?

In the example below I would like access to the headers and principal in the Validate call:

    private static AuthenticationConfiguration CreateAuthenticationConfiguration()
    {
        var authentication = new AuthenticationConfiguration
            {
                ClaimsAuthenticationManager = new AuthenticationManager(),
                RequireSsl = true,
                EnableSessionToken = true
            };

        authentication.AddBasicAuthentication(AuthenticationService.Validate, "localhost");

        return authentication;
    }

**Comment by leastprivilege** [comment]
I don't think so - this code is really old. Feel free to modify it - it simply wires up a message handler in web api. Or use Katana instead.
