### ISSUE TITLE
ClaimsAuthorizationManager

### ISSUE THREAD

**Issue by nambisan** [IdentityModel/Thinktecture.IdentityModel.45#164]
Perhaps the question is misplaced (as it applies more to .NET 4.5 framework than Thinktecture.IdentityModel), but it would be nice if the CheckAccess method would return a data structure rather than boolean. 
Here's why:
Suppose the application needs to display a meaningful message to the end user stating the specific reason instead of a generic "Not authorized", how can this be done with the current framework?

**Comment by leastprivilege** [comment]
Good idea - feel free to fork the repo and make whatever changes you like.
