### ISSUE TITLE
CORS request headers are case sensitive

### ISSUE THREAD

**Issue by jaydinslage** [IdentityModel/Thinktecture.IdentityModel.45#167]
For some reason, running C# 6, IIS 10, the CORS request headers, including the Origin, are coming back all lowercase. Because of this, the comparison in the IIS HttpContextRequest.GetHeader method is failing to detect that the request is a CORS preflight request.  Basically the IsCors and IsCorsPreflight is coming back false.

As a note, the actual request at the server, viewed through Firebug, shows that the headers are capitalized as expected. I'm not currently able to determine where these headers are being modified.

**Comment by brockallen** [comment]
Perhaps in some web proxy?

**Comment by jaydinslage** [comment]
Don't have one. This is my local machine running through IIS (not IIS Express). Still looking though. Aren't HTTP headers supposed to be case insensitive?

**Comment by jaydinslage** [comment]
I'm checking the middleware, but all I have is the Identity Server 3, cookie, and related middleware.  The only modules that are running are the Identity Model CORS.  I have no custom ones and all the suggested ones have been removed.

**Comment by jaydinslage** [comment]
In Chrome it shows that the headers are all lowercase.  I've also created my own module to inspect the request.  I've looked at the HttpContext.Current.Request object and they are lowercase in there.  The only place I could see that they might be modified (if they are sent correctly) is in IIS and I've gone through that for quite some time now.  What I'm guessing, is that it is being sent that way from the client (jQuery).

**Comment by sbell** [comment]
Was this issue ever addressed?  It's my understanding that the current http spec says headers should be case-insensitive, and we're now seeing this in certain versions of FireFox and Chrome.  The result is 404s due to "Origin" being "origin", and IsCors returning false.

**Comment by leastprivilege** [comment]
I never got a PR - so no.

**Comment by leastprivilege** [comment]
This library is discontinued. I would suggest you copy whatever code you need - and take ownership.
