### ISSUE TITLE
How to expand maxclockskew for issuing security tokens using 'UserNameWSTrustBinding' via WSTrust?

### ISSUE THREAD

**Issue by hatefi-arman** [IdentityModel/Thinktecture.IdentityModel.45#168]
I am using following peace of code to issue a security token by STS using UserNameWSTrustBinding. This code works fine, if the client datetime meet the default 5 min skewclock. 
What shall I do to increase this time span to mend the situation for other clients of non-synced date & time with STS.

Code:
---------------------------
        var credentials = new ClientCredentials();
        credentials.UserName.UserName = "username";
        credentials.UserName.Password = "password";

        var stsAddress = System.Configuration.ConfigurationManager.AppSettings["ida:STSAddress"];
        var realm = System.Configuration.ConfigurationManager.AppSettings["ida:Realm"];

        var token = WSTrustClient.Issue(
            new EndpointAddress(stsAddress),
            new EndpointAddress(realm),
            UserNameWSTrustBinding(SecurityMode.TransportWithMessageCredential), 
            credentials);

        return token.ToTokenXmlString(); 

I also followed the instructions from the link bellow to create a custom binding based on 'UserNameWSTrustBinding' and setting maxclockskew of LocalClientSettings and LocalServiceSettings, but it didn't solve the issue. 
https://msdn.microsoft.com/en-us/library/aa738468(v=vs.110).aspx

Note that, we are using Thinktecture.IdentityModel, Version=3.6.1.0 on our clients and the upgrade to final version should be our last chance.

Regards,
Arman

**Comment by leastprivilege** [comment]
Well - check the source code - it internally uses WSTrustChannelFactory - which in turn uses the security token handlers. The SAML handler has the configuration bits for the clock skew.

Welcome to the simple world of WCF ;)

**Comment by hatefi-arman** [comment]
Dear Dominick,
First off, thank you for your quick reply. 
I got the issue, but as I'm new to this field of security, could you explain more how I can access SAML handler to set proper clock skew. 
I really need your help.
Thank you for your consideration.
Arman

**Comment by leastprivilege** [comment]
Hey, 

that is really a WCF question. If I find the time to dig that up (unlikely right now), I will post it here.

In the meanwhile use StackOverflow and similar for more research.
