### ISSUE TITLE
CreateAuthorizeUrl  not checking custom providerinfo endpoint already exists "?" or not

### ISSUE THREAD

**Issue by pottabathini** [IdentityModel/Thinktecture.IdentityModel.45#171]
we are trying to add custom ProviderInformation while creating OidcClientOptions object, in that we put custom URI which already contain query string.

When we call PrepareLoginAsync method it is not checking for already existing endpoint have any query parameters or not and it blindly adding "?" at the end.

We find this at: Thinktecture.IdentityModel.Clients name space Oidcclient.CreateAuthorizeUrl method

**Comment by leastprivilege** [comment]
Wrong repo
