### ISSUE TITLE
ClaimsAuthorizeAttribute defaults to controller and action name from RouteData

### ISSUE THREAD

**Issue by skajfes** [IdentityModel/Thinktecture.IdentityModel.45#66]
I am doing an MVC site and I want to display the menu only with links the current user is authorized to see, based on ClaimsAuthorize attribute on controllers and actions.

When displaying the links I construct a new AuthorizationContext object, with controllerContext and actionDescription based on the desired link, and execute the OnAuthorization() method of every IAuthorizationFilter on targeted controller.

However the problem is that ClaimsAuthorize attribute without parameters defaults to checking access to current controller and action, based on AuthorizationContext.RouteData, which is always the current page the user is on.

A workaround is to change CheckAccess method in Thinktecture.IdentityModel.Authorization.Mvc.ClaimsAuthorizeAttribute

from: 
```
var action = filterContext.RouteData.Values["action"] as string;
var controller = filterContext.RouteData.Values["controller"] as string;
return ClaimsAuthorization.CheckAccess(action, controller);
```
to: 
```
var action = filterContext.ActionDescriptor.ActionName;
var controller = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
return ClaimsAuthorization.CheckAccess(action, controller);
```

**Comment by leastprivilege** [comment]
sorry - this repo is deprecated
